spring:
  application:
    name: mentoring-platform
  datasource:
    url: jdbc:postgresql://localhost:5432/mentoring
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true


jwt:
  secret: dK6t12J4TcJ66Agu2UKiLeRmHII+MGOJwSE+9on0WgI=
  expiration: 90000