spring:
  application:
    name: mentoring-platform
  datasource:
    url: jdbc:postgresql://localhost:5432/mentoring
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: mentoring-platform
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.github.valdpq.mentoringplatform.lesson.event"


jwt:
  secret: dK6t12J4TcJ66Agu2UKiLeRmHII+MGOJwSE+9on0WgI=
  expiration: 9000000